# Datengenerierung und Zugriff
Hier möchte ich Funktionen für verschiedene Parameter kombinieren. Außerdem möchte ich die Generierung der Testdaten von der Abfrage trennen damit die Generierung später einfach durch eine Datenbankabfrage ersetzt werden kann und die Abfrage kürzer und übersichtlicher wird.

In [1]:
import pandas as pd
import numpy as np
from typing import Literal

from generate_data import create_testdata
from access_data import (
    get_meter_metadata,
    get_direction_for_meter_id,
    get_data
)

## Generate

In [4]:
df = create_testdata()
# print(df.to_string())
df

,meter_id,location,timestamp,consumption,generation,forecast
0,mp_1,Wohnhaus,2026-04-12 00:00:00+02:00,1.030472,NaN,False
1,mp_1,Wohnhaus,2026-04-12 00:15:00+02:00,0.928892,NaN,False
2,mp_1,Wohnhaus,2026-04-12 00:30:00+02:00,1.140790,NaN,False
3,mp_1,Wohnhaus,2026-04-12 00:45:00+02:00,1.192585,NaN,False
4,mp_1,Wohnhaus,2026-04-12 01:00:00+02:00,0.936102,NaN,False
...,...,...,...,...,...,...
67,mp_4,Firma,2026-04-16 19:00:00+02:00,NaN,0.607129,True
68,mp_4,Firma,2026-04-16 20:00:00+02:00,NaN,0.823419,True
69,mp_4,Firma,2026-04-16 21:00:00+02:00,NaN,0.804801,True
70,mp_4,Firma,2026-04-16 22:00:00+02:00,NaN,0.784051,True
71,mp_4,Firma,2026-04-16 23:00:00+02:00,NaN,0.886671,True

## Access

### Metadaten

In [3]:
payload = {
    "metadata": get_meter_metadata(df).to_dict(orient="records"),
    "unit": "kWh"
}

payload

{'metadata': [{'meter_id': 'mp_1',
   'location': 'Wohnhaus',
   'direction': 'consumption'},
  {'meter_id': 'mp_2', 'location': 'Wohnhaus', 'direction': 'generation'},
  {'meter_id': 'mp_3', 'location': 'Firma', 'direction': 'consumption'},
  {'meter_id': 'mp_4', 'location': 'Firma', 'direction': 'generation'}],
 'unit': 'kWh'}

### Timeseries

In [4]:
get_data(
    df=df,
    meter_id="mp_1",
    location=None,
    start=None,
    end=None,
    forecast=None
)

,meter_id,location,timestamp,consumption,generation,forecast
0,mp_1,Wohnhaus,2026-04-11 00:00:00+02:00,1.030472,NaN,False
1,mp_1,Wohnhaus,2026-04-11 00:15:00+02:00,0.928892,NaN,False
2,mp_1,Wohnhaus,2026-04-11 00:30:00+02:00,1.140790,NaN,False
3,mp_1,Wohnhaus,2026-04-11 00:45:00+02:00,1.192585,NaN,False
4,mp_1,Wohnhaus,2026-04-11 01:00:00+02:00,0.936102,NaN,False
...,...,...,...,...,...,...
259,mp_1,Wohnhaus,2026-04-15 19:00:00+02:00,0.607129,NaN,True
260,mp_1,Wohnhaus,2026-04-15 20:00:00+02:00,0.823419,NaN,True
261,mp_1,Wohnhaus,2026-04-15 21:00:00+02:00,0.804801,NaN,True
262,mp_1,Wohnhaus,2026-04-15 22:00:00+02:00,0.784051,NaN,True
263,mp_1,Wohnhaus,2026-04-15 23:00:00+02:00,0.886671,NaN,True

In [6]:
# optimieren: Redundanzen vermeiden
def get_data_sample(df, meter_id, start, end, max_points=100):
    data = get_data(df, meter_id=meter_id, start=start, end=end)

    # falls zu viele Daten → runter sampeln
    print(len(data))
    if len(data) > max_points:
        data = data.iloc[::len(data)//max_points]

    return data.to_dict(orient="records")

get_data_sample(df, "mp_1", "2026-04-11", "2026-04-16")

264

[{'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 00:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.030471707975443,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 00:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.140790180638568,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 01:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.9361021181919439,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 01:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.2088825142500133,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 02:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.2584626585309833,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 02:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.4110012098809195,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 03:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.3911852031682976,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 03:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.4911896656171137,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 04:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.5392472796167596,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 04:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.6459768894236932,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 05:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.5929901920094207,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 05:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.7844292153246755,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 06:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.6671756585195772,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 06:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.808000445313714,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 07:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.8375379152580718,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 07:30:00+0200', tz='Europe/Vienna'),
  'consumption': 2.0484790295271242,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 08:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.817529455614209,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 08:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.961031950823497,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 09:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.9148276073529802,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 09:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.8665547249251078,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 10:00:00+0200', tz='Europe/Vienna'),
  'consumption': 2.042002332477629,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 10:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.9156127845276278,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 11:00:00+0200', tz='Europe/Vienna'),
  'consumption': 2.0040692611880924,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 11:30:00+0200', tz='Europe/Vienna'),
  'consumption': 2.0854862720679614,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 12:00:00+0200', tz='Europe/Vienna'),
  'consumption': 2.06785753887903,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 12:30:00+0200', tz='Europe/Vienna'),
  'consumption': 2.02617396308162,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 13:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.8445270353616265,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 13:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.9319010731752044,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 14:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.935883876538424,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 14:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.8571060390135612,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 15:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.7516097906920247,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 15:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.9083992118600468,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 16:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.9316133968363953,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 16:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.7902616408360386,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 17:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.8720047123780883,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 17:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.6163094759885257,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 18:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.606385033300951,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 18:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.6640032484082792,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 19:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.5556542475573887,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 19:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.6069681445871884,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 20:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.533760512578923,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 20:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.3933395068322798,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 21:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.2497637157680757,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 21:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.2605120330174666,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 22:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.292301144782453,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 22:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.2464824107144699,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 23:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.072552855370829,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-11 23:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.8805909217549623,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 00:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.8512826513268859,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 00:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.9578294520375488,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 01:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.8146906527540961,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 01:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.7521736063158666,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 02:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.630649540014677,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 02:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.5664146361284096,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 03:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.6843182701184511,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 03:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.5843300292254419,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 04:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.4240595000249837,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 04:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.4355093314951902,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 05:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.39885970228293516,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 05:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.48576754245563547,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 06:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.17615571319473228,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 06:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.2565429146640467,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 07:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.2774043579862802,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 07:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.30306160938908644,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 08:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.05924315669973851,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 08:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.05451823614738764,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 09:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.13121773172422002,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 09:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.0,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 10:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.05965744602146217,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 10:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.214549626785659,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 11:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.04715067909672623,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 11:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.0,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 12:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.0,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 12:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.0,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 13:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.11878136379713894,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 13:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.008688431281038331,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 14:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.0,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 14:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.05650159105018464,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 15:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.0997051336933896,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 15:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.06549798862057002,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 16:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.05149336731755816,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 16:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.39711617410546696,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 17:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.3079120223944199,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 17:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.3603718563542172,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 18:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.29787304984106777,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 18:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.2973507452191021,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 19:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.36938093845983805,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 19:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.3416671731161428,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 20:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.684247392661749,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 20:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.5734013497199638,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 21:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.7765868683484897,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 21:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.6671473317889766,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 22:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.8146315321178783,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 22:30:00+0200', tz='Europe/Vienna'),
  'consumption': 0.8545827991171828,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 23:00:00+0200', tz='Europe/Vienna'),
  'consumption': 0.7646554237527446,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-12 23:30:00+0200', tz='Europe/Vienna'),
  'consumption': 1.1394762467944877,
  'generation': nan,
  'forecast': False},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-13 00:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.030471707975443,
  'generation': nan,
  'forecast': True},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-13 02:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.2511136346266818,
  'generation': nan,
  'forecast': True},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',
  'timestamp': Timestamp('2026-04-13 04:00:00+0200', tz='Europe/Vienna'),
  'consumption': 1.1515323963372357,
  'generation': nan,
  'forecast': True},
 {'meter_id': 'mp_1',
  'location': 'Wohnhaus',

## Plot

In [22]:
def get_direction_for_meter_id(df: pd.DataFrame, meter_id: str) -> str:
    meta = get_meter_metadata(df)
    return meta.loc[
        meta["meter_id"] == meter_id, "direction"
    ].iloc[0]

get_direction_for_meter_id(df, "mp_1")

'consumption'

In [14]:
import matplotlib.pyplot as plt
import uuid
import os

PLOT_DIR = "plots"
os.makedirs(PLOT_DIR, exist_ok=True)

def create_timeseries_plot(df, meter_id=None, start=None, end=None, forecast=None, metric=None):
    # Daten holen
    data = get_data(
        df,
        meter_id=meter_id,
        start=start,
        end=end,
        forecast=forecast
    )

    # richtige Spalte wählen
    if metric not in ["consumption", "generation"]:
        raise ValueError("Invalid metric")

    series = data[["timestamp", metric]].dropna()

    # Plot
    plt.figure()
    plt.plot(series["timestamp"], series[metric])
    plt.xlabel("Time")
    plt.ylabel(f"{metric} (kWh)")
    plt.title(f"{metric} for {meter_id}")

    # Datei speichern
    filename = f"{uuid.uuid4()}.png"
    # filename = f"{meter_id}_{metric}_{start}_{end}.png"
    filepath = os.path.join(PLOT_DIR, filename)

    plt.savefig(filepath)
    plt.close()

    return filename

create_timeseries_plot(
    df=df,
    meter_id="mp_1",
    end="2026-04-16",
    metric="generation")

'ef5959a0-b867-4f7d-9707-3761046b1c32.png'

## Json

In [ ]:
tools = [
  {
    "type": "function",
    "function": {
      "name": "generate_series",
      "description": "Generate synthetic electricity demand (consumption) time series data.",
      "parameters": {
        "type": "object",
        "properties": {
          "start": {
            "type": "string",
            "format": "date-time",
            "description": "Start timestamp in ISO 8601 format (e.g. 2026-01-01T00:00:00)"
          },
          "end": {
            "type": "string",
            "format": "date-time",
            "description": "End timestamp in ISO 8601 format (e.g. 2026-01-01T23:00:00)"
          },
          "pattern": {
            "type": "string",
            "enum": ["residential", "industrial"],
            "description": "Consumption pattern type. Residential has peaks in the morning and evening, industrial peaks during working hours.",
            "default": "residential"
          }
        },
        "required": ["start", "end"]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "generate_production_series",
      "description": "Generate synthetic electricity supply (production) time series data.",
      "parameters": {
        "type": "object",
        "properties": {
          "start": {
            "type": "string",
            "format": "date-time",
            "description": "Start timestamp in ISO 8601 format (e.g. 2026-01-01T00:00:00)"
          },
          "end": {
            "type": "string",
            "format": "date-time",
            "description": "End timestamp in ISO 8601 format (e.g. 2026-01-01T23:00:00)"
          },
          "pattern": {
            "type": "string",
            "enum": ["residential", "industrial"],
            "description": "Production pattern type. Residential may simulate small-scale generation (e.g. solar), industrial simulates large-scale continuous production.",
            "default": "residential"
          }
        },
        "required": ["start", "end"]
      }
    }
  }
]

In [ ]:
def get_timeseries(
    meter_id: str,
    metric: str,
    start_time: str,
    end_time: str,
    include_forecast: bool = True
):
    pass